# Thermal Preference Elicitation Framework

Currently, this framework has been validated for only 1D (operating temp) feature.

In this example notebook, we consider an example case in which we assume that the utility of occupant is defined as below <img src="img.png">

# Step 1

Load required modules

In [4]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../')
from GPElicit import elicit
from Misc import visualize

# Step 2

1. Occupant walks inside the room and is exposed to state r.
2. Randomly change the state of the room to new state s.
3. Ask the occupant which state they prefer. 
4. If they say state current state s, then record y as 1. If they say previous state r, then record y as 0.
This first duel is our initial duel.
5. Put the duel value and response in the '../data/duels/duels.csv' file


In [5]:
# Load the duels file
data_file = '../data/duels/duels1.csv'

In [6]:
data = pd.read_csv(data_file)
data # check if the duels data is as you want it to be

Unnamed: 0  Tprev  Tcurrent  y    MEUI
0            0  15.00     20.00  1  0.2170
1            1  20.00     27.00  0  0.0552
2            2  27.00     15.00  0  0.0552
3            3  15.00     22.60  1  0.0274
4            4  22.60     18.40  1  0.0115
5            5  18.40     25.00  0  0.0188
6            6  25.00     21.12  1  0.0094
7            7  21.12     19.16  1  0.0120
8            8  19.16     17.69  0  0.0050
9            9  17.69     19.65  1  0.0070
10          10  19.65     20.38  0  0.0035

In [7]:
iter_num = data.shape[0]

In [8]:
Tprev = np.array(data.Tprev) # previous state (operating temp.)
Tcurrent = np.array(data.Tcurrent) # current state <---- elicitation framework will give you this values
X = np.vstack([[Tprev, Tcurrent]]).T
X = X.astype(float) # features need to be float
Y = np.array(data.y)[:,None] # response of the occupant <---- you need to ask occupant about this

# Step 3

Now, we want to find the next elicited state. So, we need to use **elicit** module.

In [9]:
config_file = '../config_files/thermal_config.json' # configuration for grid (how fine you want to be)
trial_num = 1 # this is just to save all the plots in '../data/results/T1' if trial_num = 1 ; T2 if trial_num = 2

In [21]:
Aq = elicit.Aquisition(X,Y, config_file)

burn-in sampling started
Iteration:  100 	 Acc Rate:  98.0 %
Iteration:  200 	 Acc Rate:  99.0 %
Iteration:  300 	 Acc Rate:  99.0 %
Iteration:  400 	 Acc Rate:  100.0 %
Iteration:  500 	 Acc Rate:  100.0 %
burn-in sampling ended
Iteration:  100 	 Acc Rate:  98.0 %
Iteration:  200 	 Acc Rate:  100.0 %
Iteration:  300 	 Acc Rate:  100.0 %
Iteration:  400 	 Acc Rate:  99.0 %
Iteration:  500 	 Acc Rate:  100.0 %
Iteration:  600 	 Acc Rate:  100.0 %
Iteration:  700 	 Acc Rate:  100.0 %
Iteration:  800 	 Acc Rate:  99.0 %
Iteration:  900 	 Acc Rate:  98.0 %
Iteration:  1000 	 Acc Rate:  100.0 %
Iteration:  1100 	 Acc Rate:  100.0 %
Iteration:  1200 	 Acc Rate:  99.0 %
Iteration:  1300 	 Acc Rate:  100.0 %
Iteration:  1400 	 Acc Rate:  100.0 %
Iteration:  1500 	 Acc Rate:  100.0 %
Iteration:  1600 	 Acc Rate:  100.0 %
Iteration:  1700 	 Acc Rate:  99.0 %
Iteration:  1800 	 Acc Rate:  100.0 %
Iteration:  1900 	 Acc Rate:  99.0 %
Iteration:  2000 	 Acc Rate:  100.0 %
[20.38]


In [29]:
Aq.Xreachablenorm

array([[0.        ],
       [0.00907029],
       [0.01814059],
       [0.02721088],
       [0.03628118],
       [0.04535147],
       [0.05442177],
       [0.06349206],
       [0.07256236],
       [0.08163265],
       [0.09070295],
       [0.09977324],
       [0.10884354],
       [0.11791383],
       [0.12698413],
       [0.13605442],
       [0.14512472],
       [0.15419501],
       [0.16326531],
       [0.1723356 ],
       [0.1814059 ],
       [0.19047619],
       [0.19954649],
       [0.20861678],
       [0.21768707],
       [0.22675737],
       [0.23582766],
       [0.24489796],
       [0.25396825],
       [0.26303855],
       [0.27210884],
       [0.28117914],
       [0.29024943],
       [0.29931973],
       [0.30839002],
       [0.31746032],
       [0.32653061],
       [0.33560091],
       [0.3446712 ],
       [0.3537415 ],
       [0.36281179],
       [0.37188209],
       [0.38095238],
       [0.39002268],
       [0.39909297],
       [0.40816327],
       [0.41723356],
       [0.426

In [28]:
Aq.Xreachablenorm[:,0:]

array([[0.        ],
       [0.00907029],
       [0.01814059],
       [0.02721088],
       [0.03628118],
       [0.04535147],
       [0.05442177],
       [0.06349206],
       [0.07256236],
       [0.08163265],
       [0.09070295],
       [0.09977324],
       [0.10884354],
       [0.11791383],
       [0.12698413],
       [0.13605442],
       [0.14512472],
       [0.15419501],
       [0.16326531],
       [0.1723356 ],
       [0.1814059 ],
       [0.19047619],
       [0.19954649],
       [0.20861678],
       [0.21768707],
       [0.22675737],
       [0.23582766],
       [0.24489796],
       [0.25396825],
       [0.26303855],
       [0.27210884],
       [0.28117914],
       [0.29024943],
       [0.29931973],
       [0.30839002],
       [0.31746032],
       [0.32653061],
       [0.33560091],
       [0.3446712 ],
       [0.3537415 ],
       [0.36281179],
       [0.37188209],
       [0.38095238],
       [0.39002268],
       [0.39909297],
       [0.40816327],
       [0.41723356],
       [0.426

In [10]:
next_state, next_duel, meanexp, max_exp_imp = elicit.Aquisition(X,Y, config_file).EUI(iter_num,
                                                                                     trial_num, savefig = True)

burn-in sampling started
Iteration:  100 	 Acc Rate:  98.0 %
Iteration:  200 	 Acc Rate:  100.0 %
Iteration:  300 	 Acc Rate:  99.0 %
Iteration:  400 	 Acc Rate:  100.0 %
Iteration:  500 	 Acc Rate:  100.0 %
burn-in sampling ended
Iteration:  100 	 Acc Rate:  98.0 %
Iteration:  200 	 Acc Rate:  100.0 %
Iteration:  300 	 Acc Rate:  100.0 %
Iteration:  400 	 Acc Rate:  100.0 %
Iteration:  500 	 Acc Rate:  100.0 %
Iteration:  600 	 Acc Rate:  100.0 %
Iteration:  700 	 Acc Rate:  99.0 %
Iteration:  800 	 Acc Rate:  100.0 %
Iteration:  900 	 Acc Rate:  100.0 %
Iteration:  1000 	 Acc Rate:  100.0 %
Iteration:  1100 	 Acc Rate:  99.0 %
Iteration:  1200 	 Acc Rate:  100.0 %
Iteration:  1300 	 Acc Rate:  100.0 %
Iteration:  1400 	 Acc Rate:  99.0 %
Iteration:  1500 	 Acc Rate:  100.0 %
Iteration:  1600 	 Acc Rate:  100.0 %
Iteration:  1700 	 Acc Rate:  100.0 %
Iteration:  1800 	 Acc Rate:  99.0 %
Iteration:  1900 	 Acc Rate:  98.0 %
Iteration:  2000 	 Acc Rate:  100.0 %
[20.38]


## Step 3 is the most important step. It outputs next state.

# next_state ?

In [11]:
next_state

array([18.67346939])

# next duel ?

One of the state is always shared between two duels. So, this is nothing but concatenation of next_state with previous.

In [12]:
next_duel

array([20.38      , 18.67346939])

# max EUI ?

In [13]:
max_exp_imp

0.005109645629785789

# Step 4 (Sanity checks)

Is our framework on the right track?

Check -
1. Max Expected Improvement value (is it less than the previous iteration's expected improvement? If so, GOOD!
2. Check the Expected Improvement plots. This will be saved automatically in '../data/results/T1/exp_imp_plots/iteration_num'.
3. Also check utility samples, how they look? Do they make sense? Is our framework going towards max? Some utility samples will also be saved in '../data/results/T1/utility_samples/iteration_num'.

# Step 5

1. Once you have verified that the framework is on the right track, change the operating temp of the room to the next_state as above. 
2. Its fine if you are not able to acheive the next state accurately, just record the measured next state value.
2. Ask the occupant again, which state does he prefer.
3. Add the new measured state and response to the csv  '../data/duels/duels.csv' file.
4. Add max_exp_imp to the MEUI column.
5. Run the notebook again with updated csv file.
6. As you progress with the elicitation, you will notice that the ratio $(MEUI_{(i+1)} - MEUI_{(i)})/MEUI_{(i)}$ will decrease. Based on pilot study, stop the elicitation, once the ratio becomes small enough.

# Validation (This is just for playing around with the framework)

In [14]:
from SynOccupant import datagen

In [15]:
DObject = datagen.ThermalPrefDataGen(config_file)
ynew = DObject.response_gen1D(next_duel[:,None].T)

In [16]:
ynew

array([1])

In [17]:
next_duel

array([20.38      , 18.67346939])

## Add response, new duel and MEUI to csv file and run again

In [18]:
MEUI = np.array(data.MEUI)

In [19]:
ratios = (MEUI[:-1] - MEUI[1:])/MEUI[1:]

In [20]:
ratios[:,None]

array([[ 2.93115942],
       [ 0.        ],
       [ 1.01459854],
       [ 1.3826087 ],
       [-0.38829787],
       [ 1.        ],
       [-0.21666667],
       [ 1.4       ],
       [-0.28571429],
       [ 1.        ]])